version: "3.3"
services:
    node:
        image: oven/bun:alpine
        command: [sh, -c, "bun install && bun ./src/app.ts"]
        env_file: .env
        restart: unless-stopped
        ports:
            - "3939:3939"
        volumes:
            - ./src:/serve/bun/src
            - ./package.json:/serve/bun/package.json
            - ./tsconfig.json:/serve/bun/tsconfig.json
            - ./bun.lockb:/serve/bun/bun.lockb
        working_dir: /serve/bun
